#include <stdio.h>
#include <stdbool.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <vector>
#include <strings.h>

#include "isa.h"

const static Instruction ISA[] =
{
    {"nop", "", {1, (unsigned char *)"\x00"}, {-1, 0, 0}},
    {"hlt", "", {1, (unsigned char *)"\x1F"}, {-1, 0, 0}},

    {"clc", "", {1, (unsigned char *)"\xC2"}, {-1, 0, 0}},
    {"stc", "", {1, (unsigned char *)"\xC3"}, {-1, 0, 0}},
    {"ei", "", {1, (unsigned char *)"\x4A"}, {-1, 0, 0}},
    {"di", "", {1, (unsigned char *)"\xEF"}, {-1, 0, 0}},

    {"adc", "a_m", {2, (unsigned char *)"\x3F\x00"}, {1, 1, 1}},
    {"adc", "a_[bc", {1, (unsigned char *)"\x4C"}, {-1, 0, 0}},
    {"adc", "a_[hl", {1, (unsigned char *)"\x4D"}, {-1, 0, 0}},
    {"adc", "a_[m", {3, (unsigned char *)"\x4B\x00\x00"}, {1, 1, 2}},
    {"adc", "a_a", {1, (unsigned char *)"\x70"}, {-1, 0, 0}},
    {"adc", "a_b", {1, (unsigned char *)"\x71"}, {-1, 0, 0}},
    {"adc", "a_c", {1, (unsigned char *)"\x72"}, {-1, 0, 0}},
    {"adc", "a_d", {1, (unsigned char *)"\x73"}, {-1, 0, 0}},
    {"adc", "a_h", {1, (unsigned char *)"\x74"}, {-1, 0, 0}},
    {"adc", "a_l", {1, (unsigned char *)"\x75"}, {-1, 0, 0}},

    {"add", "a_m", {2, (unsigned char *)"\x4E\x00"}, {1, 1, 1}},
    {"add", "a_[bc", {1, (unsigned char *)"\x5E"}, {-1, 0, 0}},
    {"add", "a_[hl", {1, (unsigned char *)"\x5F"}, {-1, 0, 0}},
    {"add", "a_[m", {3, (unsigned char *)"\x4F\x00\x00"}, {1, 1, 2}},
    {"add", "a_a", {1, (unsigned char *)"\x76"}, {-1, 0, 0}},
    {"add", "a_b", {1, (unsigned char *)"\x77"}, {-1, 0, 0}},
    {"add", "a_c", {1, (unsigned char *)"\x78"}, {-1, 0, 0}},
    {"add", "a_d", {1, (unsigned char *)"\x79"}, {-1, 0, 0}},
    {"add", "a_h", {1, (unsigned char *)"\x7A"}, {-1, 0, 0}},
    {"add", "a_l", {1, (unsigned char *)"\x7B"}, {-1, 0, 0}},

    {"and", "a_m", {2, (unsigned char *)"\x8D\x00"}, {1, 1, 1}},
    {"and", "a_[bc", {1, (unsigned char *)"\x8E"}, {-1, 0, 0}},
    {"and", "a_[hl", {1, (unsigned char *)"\x8F"}, {-1, 0, 0}},
    {"and", "a_[m", {3, (unsigned char *)"\x9F\x00\x00"}, {1, 1, 2}},
    {"and", "a_a", {1, (unsigned char *)"\x90"}, {-1, 0, 0}},
    {"and", "a_b", {1, (unsigned char *)"\x91"}, {-1, 0, 0}},
    {"and", "a_c", {1, (unsigned char *)"\x92"}, {-1, 0, 0}},
    {"and", "a_d", {1, (unsigned char *)"\x93"}, {-1, 0, 0}},
    {"and", "a_h", {1, (unsigned char *)"\x94"}, {-1, 0, 0}},
    {"and", "a_l", {1, (unsigned char *)"\x95"}, {-1, 0, 0}},
    {"and", "a_psw", {1, (unsigned char *)"\x96"}, {-1, 0, 0}},

    {"cmp", "a_m", {2, (unsigned char *)"\xD5\x00"}, {1, 1, 1}},
    {"cmp", "a_[bc", {1, (unsigned char *)"\xD6"}, {-1, 0, 0}},
    {"cmp", "a_[hl", {1, (unsigned char *)"\xD7"}, {-1, 0, 0}},
    {"cmp", "a_[m", {3, (unsigned char *)"\xD8\x00\x00"}, {1, 1, 2}},
    {"cmp", "a_a", {1, (unsigned char *)"\xD9"}, {-1, 0, 0}},
    {"cmp", "a_b", {1, (unsigned char *)"\xDA"}, {-1, 0, 0}},
    {"cmp", "a_c", {1, (unsigned char *)"\xDB"}, {-1, 0, 0}},
    {"cmp", "a_d", {1, (unsigned char *)"\xDC"}, {-1, 0, 0}},
    {"cmp", "a_h", {1, (unsigned char *)"\xDD"}, {-1, 0, 0}},
    {"cmp", "a_l", {1, (unsigned char *)"\xDE"}, {-1, 0, 0}},
    {"cmp", "a_psw", {1, (unsigned char *)"\xDF"}, {-1, 0, 0}},

    {"dec", "a", {1, (unsigned char *)"\x7F"}, {-1, 0, 0}}, 
    {"dec", "b", {1, (unsigned char *)"\xF2"}, {-1, 0, 0}}, 
    {"dec", "bc", {1, (unsigned char *)"\xF0"}, {-1, 0, 0}}, 
    {"dec", "c", {1, (unsigned char *)"\xF3"}, {-1, 0, 0}}, 
    {"dec", "d", {1, (unsigned char *)"\xF4"}, {-1, 0, 0}}, 
    {"dec", "h", {1, (unsigned char *)"\xF5"}, {-1, 0, 0}}, 
    {"dec", "hl", {1, (unsigned char *)"\xF1"}, {-1, 0, 0}}, 
    {"dec", "l", {1, (unsigned char *)"\xF6"}, {-1, 0, 0}}, 

    {"inc", "a", {1, (unsigned char *)"\x6F"}, {-1, 0, 0}},
    {"inc", "b", {1, (unsigned char *)"\xEA"}, {-1, 0, 0}}, 
    {"inc", "bc", {1, (unsigned char *)"\x69"}, {-1, 0, 0}}, 
    {"inc", "c", {1, (unsigned char *)"\xEB"}, {-1, 0, 0}}, 
    {"inc", "d", {1, (unsigned char *)"\xEC"}, {-1, 0, 0}}, 
    {"inc", "h", {1, (unsigned char *)"\xED"}, {-1, 0, 0}}, 
    {"inc", "hl", {1, (unsigned char *)"\x6A"}, {-1, 0, 0}}, 
    {"inc", "l", {1, (unsigned char *)"\xEE"}, {-1, 0, 0}}, 

    {"inp", "a_a", {2, (unsigned char *)"\xE1\xA4"}, {-1, 0, 0}},
    {"inp", "a_b", {2, (unsigned char *)"\xE2\xA4"}, {-1, 0, 0}},
    {"inp", "a_c", {2, (unsigned char *)"\xE3\xA4"}, {-1, 0, 0}},
    {"inp", "a_d", {2, (unsigned char *)"\xE4\xA4"}, {-1, 0, 0}},
    {"inp", "a_h", {2, (unsigned char *)"\xE5\xA4"}, {-1, 0, 0}},
    {"inp", "a_l", {2, (unsigned char *)"\xE6\xA4"}, {-1, 0, 0}},
    {"inp", "a_m", {3, (unsigned char *)"\xE0\x00\xA4"}, {1, 1, 1}},
    {"inp", "b_a", {2, (unsigned char *)"\xE1\xA5"}, {-1, 0, 0}},
    {"inp", "b_b", {2, (unsigned char *)"\xE2\xA5"}, {-1, 0, 0}},
    {"inp", "b_c", {2, (unsigned char *)"\xE3\xA5"}, {-1, 0, 0}},
    {"inp", "b_d", {2, (unsigned char *)"\xE4\xA5"}, {-1, 0, 0}},
    {"inp", "b_h", {2, (unsigned char *)"\xE5\xA5"}, {-1, 0, 0}},
    {"inp", "b_l", {2, (unsigned char *)"\xE6\xA5"}, {-1, 0, 0}},
    {"inp", "b_m", {3, (unsigned char *)"\xE0\x00\xA5"}, {1, 1, 1}},
    {"inp", "c_a", {2, (unsigned char *)"\xE1\xA6"}, {-1, 0, 0}},
    {"inp", "c_b", {2, (unsigned char *)"\xE2\xA6"}, {-1, 0, 0}},
    {"inp", "c_c", {2, (unsigned char *)"\xE3\xA6"}, {-1, 0, 0}},
    {"inp", "c_d", {2, (unsigned char *)"\xE4\xA6"}, {-1, 0, 0}},
    {"inp", "c_h", {2, (unsigned char *)"\xE5\xA6"}, {-1, 0, 0}},
    {"inp", "c_l", {2, (unsigned char *)"\xE6\xA6"}, {-1, 0, 0}},
    {"inp", "c_m", {3, (unsigned char *)"\xE0\x00\xA6"}, {1, 1, 1}},
    {"inp", "d_a", {2, (unsigned char *)"\xE1\xA7"}, {-1, 0, 0}},
    {"inp", "d_b", {2, (unsigned char *)"\xE2\xA7"}, {-1, 0, 0}},
    {"inp", "d_c", {2, (unsigned char *)"\xE3\xA7"}, {-1, 0, 0}},
    {"inp", "d_d", {2, (unsigned char *)"\xE4\xA7"}, {-1, 0, 0}},
    {"inp", "d_h", {2, (unsigned char *)"\xE5\xA7"}, {-1, 0, 0}},
    {"inp", "d_l", {2, (unsigned char *)"\xE6\xA7"}, {-1, 0, 0}},
    {"inp", "d_m", {3, (unsigned char *)"\xE0\x00\xA7"}, {1, 1, 1}},
    {"inp", "h_a", {2, (unsigned char *)"\xE1\xA8"}, {-1, 0, 0}},
    {"inp", "h_b", {2, (unsigned char *)"\xE2\xA8"}, {-1, 0, 0}},
    {"inp", "h_c", {2, (unsigned char *)"\xE3\xA8"}, {-1, 0, 0}},
    {"inp", "h_d", {2, (unsigned char *)"\xE4\xA8"}, {-1, 0, 0}},
    {"inp", "h_h", {2, (unsigned char *)"\xE5\xA8"}, {-1, 0, 0}},
    {"inp", "h_l", {2, (unsigned char *)"\xE6\xA8"}, {-1, 0, 0}},
    {"inp", "h_m", {3, (unsigned char *)"\xE0\x00\xA8"}, {1, 1, 1}},
    {"inp", "l_a", {2, (unsigned char *)"\xE1\xA9"}, {-1, 0, 0}},
    {"inp", "l_b", {2, (unsigned char *)"\xE2\xA9"}, {-1, 0, 0}},
    {"inp", "l_c", {2, (unsigned char *)"\xE3\xA9"}, {-1, 0, 0}},
    {"inp", "l_d", {2, (unsigned char *)"\xE4\xA9"}, {-1, 0, 0}},
    {"inp", "l_h", {2, (unsigned char *)"\xE5\xA9"}, {-1, 0, 0}},
    {"inp", "l_l", {2, (unsigned char *)"\xE6\xA9"}, {-1, 0, 0}},
    {"inp", "l_m", {3, (unsigned char *)"\xE0\x00\xA9"}, {1, 1, 1}},

    {"jmp", "[bc", {1, (unsigned char *)"\xD2"}, {-1, 0, 0}},
    {"jmp", "[hl", {1, (unsigned char *)"\xD3"}, {-1, 0, 0}},
    {"jmp", "[m", {3, (unsigned char *)"\xD1\x00\x00"}, {0, 1, 2}},
    {"jmp", "bc", {1, (unsigned char *)"\xCE"}, {-1, 0, 0}},
    {"jmp", "hl", {1, (unsigned char *)"\xCF"}, {-1, 0, 0}},
    {"jmp", "m", {3, (unsigned char *)"\xD0\x00\x00"}, {0, 1, 2}},

    {"jc", "m", {3, (unsigned char *)"\x28\x00\x00"}, {0, 1, 2}},
    {"jn", "m", {3, (unsigned char *)"\x37\x00\x00"}, {0, 1, 2}},
    {"jnc", "m", {3, (unsigned char *)"\x2A\x00\x00"}, {0, 1, 2}},
    {"jnn", "m", {3, (unsigned char *)"\x39\x00\x00"}, {0, 1, 2}},
    {"jno", "m", {3, (unsigned char *)"\x3A\x00\x00"}, {0, 1, 2}},
    {"jnz", "m", {3, (unsigned char *)"\x2B\x00\x00"}, {0, 1, 2}},
    {"jo", "m", {3, (unsigned char *)"\x38\x00\x00"}, {0, 1, 2}},
    {"jz", "m", {3, (unsigned char *)"\x29\x00\x00"}, {0, 1, 2}},

    {"jsr", "bc", {1, (unsigned char *)"\xCA"}, {-1, 0, 0}},
    {"jsr", "hl", {1, (unsigned char *)"\xCB"}, {-1, 0, 0}},
    {"jsr", "[bc", {1, (unsigned char *)"\xCC"}, {-1, 0, 0}},
    {"jsr", "[hl", {1, (unsigned char *)"\xCD"}, {-1, 0, 0}},
    {"jsr", "m", {3, (unsigned char *)"\xE8\x00\x00"}, {0, 1, 2}},
    {"jsr", "[m", {3, (unsigned char *)"\xE9\x00\x00"}, {0, 1, 2}},
    {"ret", "", {1, (unsigned char *)"\xD4"}, {-1, 0, 0}},

    {"ld", "a_[bc", {2, (unsigned char *)"\x24\x90"}, {-1, 0, 0}},
    {"ld", "a_[hl", {2, (unsigned char *)"\x25\x90"}, {-1, 0, 0}},
    {"ld", "a_[m", {3, (unsigned char *)"\x30\x00\x00"}, {1, 1, 2}},
    {"ld", "a_[pc", {2, (unsigned char *)"\x27\x90"}, {-1, 0, 0}},
    {"ld", "a_[sp", {2, (unsigned char *)"\x26\x90"}, {-1, 0, 0}},
    {"ld", "a_m", {2, (unsigned char *)"\x16\x00"}, {1, 1, 1}},
    {"ld", "b_[bc", {2, (unsigned char *)"\x24\x91"}, {-1, 0, 0}},
    {"ld", "b_[hl", {2, (unsigned char *)"\x25\x91"}, {-1, 0, 0}},
    {"ld", "b_[m", {3, (unsigned char *)"\x31\x00\x00"}, {1, 1, 2}},
    {"ld", "b_[pc", {2, (unsigned char *)"\x27\x91"}, {-1, 0, 0}},
    {"ld", "b_[sp", {2, (unsigned char *)"\x26\x91"}, {-1, 0, 0}},
    {"ld", "b_m", {2, (unsigned char *)"\x17\x00"}, {1, 1, 1}},
    {"ld", "bc_[bc", {2, (unsigned char *)"\x24\x8C"}, {-1, 0, 0}},
    {"ld", "bc_[hl", {2, (unsigned char *)"\x25\x8C"}, {-1, 0, 0}},
    {"ld", "bc_[m", {3, (unsigned char *)"\x0C\x00\x00"}, {1, 1, 2}},
    {"ld", "bc_[pc", {2, (unsigned char *)"\x27\x8C"}, {-1, 0, 0}},
    {"ld", "bc_[sp", {2, (unsigned char *)"\x26\x8C"}, {-1, 0, 0}},
    {"ld", "bc_m", {3, (unsigned char *)"\x20\x00\x00"}, {1, 1, 2}},
    {"ld", "c_[bc", {2, (unsigned char *)"\x24\x92"}, {-1, 0, 0}},
    {"ld", "c_[hl", {2, (unsigned char *)"\x25\x92"}, {-1, 0, 0}},
    {"ld", "c_[m", {3, (unsigned char *)"\x32\x00\x00"}, {1, 1, 2}},
    {"ld", "c_[pc", {2, (unsigned char *)"\x27\x92"}, {-1, 0, 0}},
    {"ld", "c_[sp", {2, (unsigned char *)"\x26\x92"}, {-1, 0, 0}},
    {"ld", "c_m", {2, (unsigned char *)"\x18\x00"}, {1, 1, 1}},
    {"ld", "d_[bc", {2, (unsigned char *)"\x24\x93"}, {-1, 0, 0}},
    {"ld", "d_[hl", {2, (unsigned char *)"\x25\x93"}, {-1, 0, 0}},
    {"ld", "d_[m", {3, (unsigned char *)"\x33\x00\x00"}, {1, 1, 2}},
    {"ld", "d_[pc", {2, (unsigned char *)"\x27\x93"}, {-1, 0, 0}},
    {"ld", "d_[sp", {2, (unsigned char *)"\x26\x93"}, {-1, 0, 0}},
    {"ld", "d_m", {2, (unsigned char *)"\x19\x00"}, {1, 1, 1}},
    {"ld", "h_[bc", {2, (unsigned char *)"\x24\x94"}, {-1, 0, 0}},
    {"ld", "h_[hl", {2, (unsigned char *)"\x25\x94"}, {-1, 0, 0}},
    {"ld", "h_[m", {3, (unsigned char *)"\x34\x00\x00"}, {1, 1, 2}},
    {"ld", "h_[pc", {2, (unsigned char *)"\x27\x94"}, {-1, 0, 0}},
    {"ld", "h_[sp", {2, (unsigned char *)"\x26\x94"}, {-1, 0, 0}},
    {"ld", "h_m", {2, (unsigned char *)"\x1A\x00"}, {1, 1, 1}},
    {"ld", "hl_[bc", {2, (unsigned char *)"\x24\x8D"}, {-1, 0, 0}},
    {"ld", "hl_[hl", {2, (unsigned char *)"\x25\x8D"}, {-1, 0, 0}},
    {"ld", "hl_[m", {3, (unsigned char *)"\x0D\x00\x00"}, {1, 1, 2}},
    {"ld", "hl_[pc", {2, (unsigned char *)"\x27\x8D"}, {-1, 0, 0}},
    {"ld", "hl_[sp", {2, (unsigned char *)"\x26\x8D"}, {-1, 0, 0}},
    {"ld", "hl_m", {3, (unsigned char *)"\x21\x00\x00"}, {1, 1, 2}},
    {"ld", "l_[bc", {2, (unsigned char *)"\x24\x95"}, {-1, 0, 0}},
    {"ld", "l_[hl", {2, (unsigned char *)"\x25\x95"}, {-1, 0, 0}},
    {"ld", "l_[m", {3, (unsigned char *)"\x35\x00\x00"}, {1, 1, 2}},
    {"ld", "l_[pc", {2, (unsigned char *)"\x27\x95"}, {-1, 0, 0}},
    {"ld", "l_[sp", {2, (unsigned char *)"\x26\x95"}, {-1, 0, 0}},
    {"ld", "l_m", {2, (unsigned char *)"\x1B\x00"}, {1, 1, 1}},
    {"ld", "pc_[bc", {2, (unsigned char *)"\x24\x8F"}, {-1, 0, 0}},
    {"ld", "pc_[hl", {2, (unsigned char *)"\x25\x8F"}, {-1, 0, 0}},
    {"ld", "pc_[m", {3, (unsigned char *)"\x0F\x00\x00"}, {1, 1, 2}},
    {"ld", "pc_[pc", {2, (unsigned char *)"\x27\x8F"}, {-1, 0, 0}},
    {"ld", "pc_[sp", {2, (unsigned char *)"\x26\x8F"}, {-1, 0, 0}},
    {"ld", "pc_m", {3, (unsigned char *)"\x23\x00\x00"}, {1, 1, 2}},
    {"ld", "psw_[bc", {2, (unsigned char *)"\x24\x96"}, {-1, 0, 0}},
    {"ld", "psw_[hl", {2, (unsigned char *)"\x25\x96"}, {-1, 0, 0}},
    {"ld", "psw_[m", {3, (unsigned char *)"\x36\x00\x00"}, {1, 1, 2}},
    {"ld", "psw_[pc", {2, (unsigned char *)"\x27\x96"}, {-1, 0, 0}},
    {"ld", "psw_[sp", {2, (unsigned char *)"\x26\x96"}, {-1, 0, 0}},
    {"ld", "psw_m", {2, (unsigned char *)"\x1C\x00"}, {1, 1, 1}},
    {"ld", "sp_[bc", {2, (unsigned char *)"\x24\x8E"}, {-1, 0, 0}},
    {"ld", "sp_[hl", {2, (unsigned char *)"\x25\x8E"}, {-1, 0, 0}},
    {"ld", "sp_[m", {3, (unsigned char *)"\x0E\x00\x00"}, {1, 1, 2}},
    {"ld", "sp_[pc", {2, (unsigned char *)"\x27\x8E"}, {-1, 0, 0}},
    {"ld", "sp_[sp", {2, (unsigned char *)"\x26\x8E"}, {-1, 0, 0}},
    {"ld", "sp_m", {3, (unsigned char *)"\x22\x00\x00"}, {1, 1, 2}},

    {"mov", "a_a", {2, (unsigned char *)"\x01\x80"}, {-1, 0, 0}},
    {"mov", "a_b", {2, (unsigned char *)"\x01\x81"}, {-1, 0, 0}},
    {"mov", "a_bc", {2, (unsigned char *)"\x10\x88"}, {-1, 0, 0}},
    {"mov", "a_c", {2, (unsigned char *)"\x01\x82"}, {-1, 0, 0}},
    {"mov", "a_d", {2, (unsigned char *)"\x01\x83"}, {-1, 0, 0}},
    {"mov", "a_h", {2, (unsigned char *)"\x01\x84"}, {-1, 0, 0}},
    {"mov", "a_hl", {2, (unsigned char *)"\x10\x89"}, {-1, 0, 0}},
    {"mov", "a_l", {2, (unsigned char *)"\x01\x85"}, {-1, 0, 0}},
    {"mov", "a_pc", {2, (unsigned char *)"\x10\x8B"}, {-1, 0, 0}},
    {"mov", "a_psw", {2, (unsigned char *)"\x01\x86"}, {-1, 0, 0}},
    {"mov", "a_sp", {2, (unsigned char *)"\x10\x8A"}, {-1, 0, 0}},
    {"mov", "b_a", {2, (unsigned char *)"\x02\x80"}, {-1, 0, 0}},
    {"mov", "b_b", {2, (unsigned char *)"\x02\x81"}, {-1, 0, 0}},
    {"mov", "b_bc", {2, (unsigned char *)"\x11\x88"}, {-1, 0, 0}},
    {"mov", "b_c", {2, (unsigned char *)"\x02\x82"}, {-1, 0, 0}},
    {"mov", "b_d", {2, (unsigned char *)"\x02\x83"}, {-1, 0, 0}},
    {"mov", "b_h", {2, (unsigned char *)"\x02\x84"}, {-1, 0, 0}},
    {"mov", "b_hl", {2, (unsigned char *)"\x11\x89"}, {-1, 0, 0}},
    {"mov", "b_l", {2, (unsigned char *)"\x02\x85"}, {-1, 0, 0}},
    {"mov", "b_pc", {2, (unsigned char *)"\x11\x8B"}, {-1, 0, 0}},
    {"mov", "b_psw", {2, (unsigned char *)"\x02\x86"}, {-1, 0, 0}},
    {"mov", "b_sp", {2, (unsigned char *)"\x11\x8A"}, {-1, 0, 0}},
    {"mov", "bc_bc", {2, (unsigned char *)"\x08\x88"}, {-1, 0, 0}},
    {"mov", "bc_hl", {2, (unsigned char *)"\x08\x89"}, {-1, 0, 0}},
    {"mov", "bc_pc", {2, (unsigned char *)"\x08\x8B"}, {-1, 0, 0}},
    {"mov", "bc_sp", {2, (unsigned char *)"\x08\x8A"}, {-1, 0, 0}},
    {"mov", "c_a", {2, (unsigned char *)"\x03\x80"}, {-1, 0, 0}},
    {"mov", "c_b", {2, (unsigned char *)"\x03\x81"}, {-1, 0, 0}},
    {"mov", "c_bc", {2, (unsigned char *)"\x12\x88"}, {-1, 0, 0}},
    {"mov", "c_c", {2, (unsigned char *)"\x03\x82"}, {-1, 0, 0}},
    {"mov", "c_d", {2, (unsigned char *)"\x03\x83"}, {-1, 0, 0}},
    {"mov", "c_h", {2, (unsigned char *)"\x03\x84"}, {-1, 0, 0}},
    {"mov", "c_hl", {2, (unsigned char *)"\x12\x89"}, {-1, 0, 0}},
    {"mov", "c_l", {2, (unsigned char *)"\x03\x85"}, {-1, 0, 0}},
    {"mov", "c_pc", {2, (unsigned char *)"\x12\x8B"}, {-1, 0, 0}},
    {"mov", "c_psw", {2, (unsigned char *)"\x03\x86"}, {-1, 0, 0}},
    {"mov", "c_sp", {2, (unsigned char *)"\x12\x8A"}, {-1, 0, 0}},
    {"mov", "d_a", {2, (unsigned char *)"\x04\x80"}, {-1, 0, 0}},
    {"mov", "d_b", {2, (unsigned char *)"\x04\x81"}, {-1, 0, 0}},
    {"mov", "d_bc", {2, (unsigned char *)"\x13\x88"}, {-1, 0, 0}},
    {"mov", "d_c", {2, (unsigned char *)"\x04\x82"}, {-1, 0, 0}},
    {"mov", "d_d", {2, (unsigned char *)"\x04\x83"}, {-1, 0, 0}},
    {"mov", "d_h", {2, (unsigned char *)"\x04\x84"}, {-1, 0, 0}},
    {"mov", "d_hl", {2, (unsigned char *)"\x13\x89"}, {-1, 0, 0}},
    {"mov", "d_l", {2, (unsigned char *)"\x04\x85"}, {-1, 0, 0}},
    {"mov", "d_pc", {2, (unsigned char *)"\x13\x8B"}, {-1, 0, 0}},
    {"mov", "d_psw", {2, (unsigned char *)"\x04\x86"}, {-1, 0, 0}},
    {"mov", "d_sp", {2, (unsigned char *)"\x13\x8A"}, {-1, 0, 0}},
    {"mov", "h_a", {2, (unsigned char *)"\x05\x80"}, {-1, 0, 0}},
    {"mov", "h_b", {2, (unsigned char *)"\x05\x81"}, {-1, 0, 0}},
    {"mov", "h_bc", {2, (unsigned char *)"\x14\x88"}, {-1, 0, 0}},
    {"mov", "h_c", {2, (unsigned char *)"\x05\x82"}, {-1, 0, 0}},
    {"mov", "h_d", {2, (unsigned char *)"\x05\x83"}, {-1, 0, 0}},
    {"mov", "h_h", {2, (unsigned char *)"\x05\x84"}, {-1, 0, 0}},
    {"mov", "h_hl", {2, (unsigned char *)"\x14\x89"}, {-1, 0, 0}},
    {"mov", "h_l", {2, (unsigned char *)"\x05\x85"}, {-1, 0, 0}},
    {"mov", "h_pc", {2, (unsigned char *)"\x14\x8B"}, {-1, 0, 0}},
    {"mov", "h_psw", {2, (unsigned char *)"\x05\x86"}, {-1, 0, 0}},
    {"mov", "h_sp", {2, (unsigned char *)"\x14\x8A"}, {-1, 0, 0}},
    {"mov", "hl_bc", {2, (unsigned char *)"\x09\x88"}, {-1, 0, 0}},
    {"mov", "hl_hl", {2, (unsigned char *)"\x09\x89"}, {-1, 0, 0}},
    {"mov", "hl_pc", {2, (unsigned char *)"\x09\x8B"}, {-1, 0, 0}},
    {"mov", "hl_sp", {2, (unsigned char *)"\x09\x8A"}, {-1, 0, 0}},
    {"mov", "l_a", {2, (unsigned char *)"\x06\x80"}, {-1, 0, 0}},
    {"mov", "l_b", {2, (unsigned char *)"\x06\x81"}, {-1, 0, 0}},
    {"mov", "l_bc", {2, (unsigned char *)"\x15\x88"}, {-1, 0, 0}},
    {"mov", "l_c", {2, (unsigned char *)"\x06\x82"}, {-1, 0, 0}},
    {"mov", "l_d", {2, (unsigned char *)"\x06\x83"}, {-1, 0, 0}},
    {"mov", "l_h", {2, (unsigned char *)"\x06\x84"}, {-1, 0, 0}},
    {"mov", "l_hl", {2, (unsigned char *)"\x15\x89"}, {-1, 0, 0}},
    {"mov", "l_l", {2, (unsigned char *)"\x06\x85"}, {-1, 0, 0}},
    {"mov", "l_pc", {2, (unsigned char *)"\x15\x8B"}, {-1, 0, 0}},
    {"mov", "l_psw", {2, (unsigned char *)"\x06\x86"}, {-1, 0, 0}},
    {"mov", "l_sp", {2, (unsigned char *)"\x15\x8A"}, {-1, 0, 0}},
    {"mov", "pc_bc", {2, (unsigned char *)"\x0B\x88"}, {-1, 0, 0}},
    {"mov", "pc_hl", {2, (unsigned char *)"\x0B\x89"}, {-1, 0, 0}},
    {"mov", "pc_pc", {2, (unsigned char *)"\x0B\x8B"}, {-1, 0, 0}},
    {"mov", "pc_sp", {2, (unsigned char *)"\x0B\x8A"}, {-1, 0, 0}},
    {"mov", "psw_a", {2, (unsigned char *)"\x07\x80"}, {-1, 0, 0}},
    {"mov", "psw_b", {2, (unsigned char *)"\x07\x81"}, {-1, 0, 0}},
    {"mov", "psw_c", {2, (unsigned char *)"\x07\x82"}, {-1, 0, 0}},
    {"mov", "psw_d", {2, (unsigned char *)"\x07\x83"}, {-1, 0, 0}},
    {"mov", "psw_h", {2, (unsigned char *)"\x07\x84"}, {-1, 0, 0}},
    {"mov", "psw_l", {2, (unsigned char *)"\x07\x85"}, {-1, 0, 0}},
    {"mov", "psw_psw", {2, (unsigned char *)"\x07\x86"}, {-1, 0, 0}},
    {"mov", "sp_bc", {2, (unsigned char *)"\x0A\x88"}, {-1, 0, 0}},
    {"mov", "sp_hl", {2, (unsigned char *)"\x0A\x89"}, {-1, 0, 0}},
    {"mov", "sp_pc", {2, (unsigned char *)"\x0A\x8B"}, {-1, 0, 0}},
    {"mov", "sp_sp", {2, (unsigned char *)"\x0A\x8A"}, {-1, 0, 0}},

    {"movsx", "bc_a", {1, (unsigned char *)"\x1D"}, {-1, 0, 0}},
    {"movsx", "hl_a", {1, (unsigned char *)"\x1E"}, {-1, 0, 0}},

    {"neg", "[m", {3, (unsigned char *)"\xC4\x00\x00"}, {0, 1, 2}},
    {"neg", "a", {1, (unsigned char *)"\xC5"}, {-1, 0, 0}},
    {"neg", "[bc", {1, (unsigned char *)"\xC6"}, {-1, 0, 0}},
    {"neg", "[hl", {1, (unsigned char *)"\xC7"}, {-1, 0, 0}},

    {"not", "[m", {3, (unsigned char *)"\xAE"}, {0, 1, 2}},
    {"not", "a", {1, (unsigned char *)"\xAF"}, {-1, 0, 0}},
    {"not", "[bc", {1, (unsigned char *)"\xC8"}, {-1, 0, 0}},
    {"not", "[hl", {1, (unsigned char *)"\xC9"}, {-1, 0, 0}},

    {"or", "a_m", {2, (unsigned char *)"\x9E\x00"}, {1, 1, 1}}, 
    {"or", "a_[bc", {1, (unsigned char *)"\xAB"}, {-1, 0, 0}}, 
    {"or", "a_[hl", {1, (unsigned char *)"\xAC"}, {-1, 0, 0}}, 
    {"or", "a_[m", {3, (unsigned char *)"\xAD"}, {1, 1, 2}}, 
    {"or", "a_a", {1, (unsigned char *)"\x97"}, {-1, 0, 0}}, 
    {"or", "a_b", {1, (unsigned char *)"\x98"}, {-1, 0, 0}}, 
    {"or", "a_c", {1, (unsigned char *)"\x99"}, {-1, 0, 0}}, 
    {"or", "a_d", {1, (unsigned char *)"\x9A"}, {-1, 0, 0}}, 
    {"or", "a_h", {1, (unsigned char *)"\x9B"}, {-1, 0, 0}}, 
    {"or", "a_l", {1, (unsigned char *)"\x9C"}, {-1, 0, 0}}, 
    {"or", "a_psw", {1, (unsigned char *)"\x9D"}, {-1, 0, 0}}, 

    {"out", "a_a", {2, (unsigned char *)"\xE1\xAA"}, {-1, 0, 0}},
    {"out", "a_b", {2, (unsigned char *)"\xE2\xAA"}, {-1, 0, 0}},
    {"out", "a_c", {2, (unsigned char *)"\xE3\xAA"}, {-1, 0, 0}},
    {"out", "a_d", {2, (unsigned char *)"\xE4\xAA"}, {-1, 0, 0}},
    {"out", "a_h", {2, (unsigned char *)"\xE5\xAA"}, {-1, 0, 0}},
    {"out", "a_l", {2, (unsigned char *)"\xE6\xAA"}, {-1, 0, 0}},
    {"out", "a_m", {3, (unsigned char *)"\xE0\x00\xAA"}, {1, 1, 1}}, 
    {"out", "b_a", {2, (unsigned char *)"\xE1\xAB"}, {-1, 0, 0}},
    {"out", "b_b", {2, (unsigned char *)"\xE2\xAB"}, {-1, 0, 0}},
    {"out", "b_c", {2, (unsigned char *)"\xE3\xAB"}, {-1, 0, 0}},
    {"out", "b_d", {2, (unsigned char *)"\xE4\xAB"}, {-1, 0, 0}},
    {"out", "b_h", {2, (unsigned char *)"\xE5\xAB"}, {-1, 0, 0}},
    {"out", "b_l", {2, (unsigned char *)"\xE6\xAB"}, {-1, 0, 0}},
    {"out", "b_m", {3, (unsigned char *)"\xE0\x00\xAB"}, {1, 1, 1}},
    {"out", "c_a", {2, (unsigned char *)"\xE1\xAC"}, {-1, 0, 0}},
    {"out", "c_b", {2, (unsigned char *)"\xE2\xAC"}, {-1, 0, 0}},
    {"out", "c_c", {2, (unsigned char *)"\xE3\xAC"}, {-1, 0, 0}},
    {"out", "c_d", {2, (unsigned char *)"\xE4\xAC"}, {-1, 0, 0}},
    {"out", "c_h", {2, (unsigned char *)"\xE5\xAC"}, {-1, 0, 0}},
    {"out", "c_l", {2, (unsigned char *)"\xE6\xAC"}, {-1, 0, 0}},
    {"out", "c_m", {3, (unsigned char *)"\xE0\x00\xAC"}, {1, 1, 1}},
    {"out", "d_a", {2, (unsigned char *)"\xE1\xAD"}, {-1, 0, 0}},
    {"out", "d_b", {2, (unsigned char *)"\xE2\xAD"}, {-1, 0, 0}},
    {"out", "d_c", {2, (unsigned char *)"\xE3\xAD"}, {-1, 0, 0}},
    {"out", "d_d", {2, (unsigned char *)"\xE4\xAD"}, {-1, 0, 0}},
    {"out", "d_h", {2, (unsigned char *)"\xE5\xAD"}, {-1, 0, 0}},
    {"out", "d_l", {2, (unsigned char *)"\xE6\xAD"}, {-1, 0, 0}},
    {"out", "d_m", {3, (unsigned char *)"\xE0\x00\xAD"}, {1, 1, 1}},
    {"out", "h_a", {2, (unsigned char *)"\xE1\xAE"}, {-1, 0, 0}},
    {"out", "h_b", {2, (unsigned char *)"\xE2\xAE"}, {-1, 0, 0}},
    {"out", "h_c", {2, (unsigned char *)"\xE3\xAE"}, {-1, 0, 0}},
    {"out", "h_d", {2, (unsigned char *)"\xE4\xAE"}, {-1, 0, 0}},
    {"out", "h_h", {2, (unsigned char *)"\xE5\xAE"}, {-1, 0, 0}},
    {"out", "h_l", {2, (unsigned char *)"\xE6\xAE"}, {-1, 0, 0}},
    {"out", "h_m", {3, (unsigned char *)"\xE0\x00\xAE"}, {1, 1, 1}},
    {"out", "l_a", {2, (unsigned char *)"\xE1\xAF"}, {-1, 0, 0}},
    {"out", "l_b", {2, (unsigned char *)"\xE2\xAF"}, {-1, 0, 0}},
    {"out", "l_c", {2, (unsigned char *)"\xE3\xAF"}, {-1, 0, 0}},
    {"out", "l_d", {2, (unsigned char *)"\xE4\xAF"}, {-1, 0, 0}},
    {"out", "l_h", {2, (unsigned char *)"\xE5\xAF"}, {-1, 0, 0}},
    {"out", "l_l", {2, (unsigned char *)"\xE6\xAF"}, {-1, 0, 0}},
    {"out", "l_m", {3, (unsigned char *)"\xE0\x00\xAF"}, {1, 1, 1}},

    {"pop", "a", {1, (unsigned char *)"\x57"}, {-1, 0, 0}},
    {"pop", "b", {1, (unsigned char *)"\x58"}, {-1, 0, 0}},
    {"pop", "c", {1, (unsigned char *)"\x59"}, {-1, 0, 0}},
    {"pop", "d", {1, (unsigned char *)"\x5A"}, {-1, 0, 0}},
    {"pop", "h", {1, (unsigned char *)"\x5B"}, {-1, 0, 0}},
    {"pop", "l", {1, (unsigned char *)"\x5C"}, {-1, 0, 0}},
    {"pop", "psw", {1, (unsigned char *)"\x5D"}, {-1, 0, 0}},
    {"pop", "bc", {1, (unsigned char *)"\x60"}, {-1, 0, 0}},
    {"pop", "hl", {1, (unsigned char *)"\x61"}, {-1, 0, 0}},
    {"pop", "pc", {1, (unsigned char *)"\x62"}, {-1, 0, 0}},

    {"psh", "a", {1, (unsigned char *)"\x50"}, {-1, 0, 0}},
    {"psh", "b", {1, (unsigned char *)"\x51"}, {-1, 0, 0}},
    {"psh", "c", {1, (unsigned char *)"\x52"}, {-1, 0, 0}},
    {"psh", "d", {1, (unsigned char *)"\x53"}, {-1, 0, 0}},
    {"psh", "h", {1, (unsigned char *)"\x54"}, {-1, 0, 0}},
    {"psh", "l", {1, (unsigned char *)"\x55"}, {-1, 0, 0}},
    {"psh", "psw", {1, (unsigned char *)"\x56"}, {-1, 0, 0}},
    {"psh", "bc", {1, (unsigned char *)"\x47"}, {-1, 0, 0}},
    {"psh", "hl", {1, (unsigned char *)"\x48"}, {-1, 0, 0}},
    {"psh", "pc", {1, (unsigned char *)"\x49"}, {-1, 0, 0}},

    {"sbb", "a_m", {2, (unsigned char *)"\x6B\x00"}, {1, 1, 1}},
    {"sbb", "a_[bc", {1, (unsigned char *)"\x6C"}, {-1, 0, 0}},
    {"sbb", "a_[hl", {1, (unsigned char *)"\x6D"}, {-1, 0, 0}},
    {"sbb", "a_[m", {3, (unsigned char *)"\x6E\x00\x00"}, {1, 1, 2}},
    {"sbb", "a_a", {1, (unsigned char *)"\x80"}, {-1, 0, 0}},
    {"sbb", "a_b", {1, (unsigned char *)"\x81"}, {-1, 0, 0}},
    {"sbb", "a_c", {1, (unsigned char *)"\x82"}, {-1, 0, 0}},
    {"sbb", "a_d", {1, (unsigned char *)"\x83"}, {-1, 0, 0}},
    {"sbb", "a_h", {1, (unsigned char *)"\x84"}, {-1, 0, 0}},
    {"sbb", "a_l", {1, (unsigned char *)"\x85"}, {-1, 0, 0}},

    {"sub", "a_m", {2, (unsigned char *)"\x7C\x00"}, {1, 1, 1}},
    {"sub", "a_[bc", {1, (unsigned char *)"\x7D"}, {-1, 0, 0}},
    {"sub", "a_[hl", {1, (unsigned char *)"\x7E"}, {-1, 0, 0}},
    {"sub", "a_[m", {3, (unsigned char *)"\x8C\x00\x00"}, {1, 1, 2}},
    {"sub", "a_a", {1, (unsigned char *)"\x86"}, {-1, 0, 0}},
    {"sub", "a_b", {1, (unsigned char *)"\x87"}, {-1, 0, 0}},
    {"sub", "a_c", {1, (unsigned char *)"\x88"}, {-1, 0, 0}},
    {"sub", "a_d", {1, (unsigned char *)"\x89"}, {-1, 0, 0}},
    {"sub", "a_h", {1, (unsigned char *)"\x8A"}, {-1, 0, 0}},
    {"sub", "a_l", {1, (unsigned char *)"\x8B"}, {-1, 0, 0}},

    {"shlc", "a", {1, (unsigned char *)"\xB0"}, {-1, 0, 0}},
    {"shlc", "[bc", {1, (unsigned char *)"\xB1"}, {-1, 0, 0}},
    {"shlc", "[hl", {1, (unsigned char *)"\xB2"}, {-1, 0, 0}},
    {"shl", "a", {1, (unsigned char *)"\xB3"}, {-1, 0, 0}},
    {"shl", "[bc", {1, (unsigned char *)"\xB4"}, {-1, 0, 0}},
    {"shl", "[hl", {1, (unsigned char *)"\xB5"}, {-1, 0, 0}},
    {"rol", "a", {1, (unsigned char *)"\xC0"}, {-1, 0, 0}},
    {"rol", "[bc", {1, (unsigned char *)"\xBC"}, {-1, 0, 0}},
    {"rol", "[hl", {1, (unsigned char *)"\xBD"}, {-1, 0, 0}},

    {"shrc", "a", {1, (unsigned char *)"\xB6"}, {-1, 0, 0}},
    {"shrc", "[bc", {1, (unsigned char *)"\xB7"}, {-1, 0, 0}},
    {"shrc", "[hl", {1, (unsigned char *)"\xB8"}, {-1, 0, 0}},
    {"shr", "a", {1, (unsigned char *)"\xB9"}, {-1, 0, 0}},
    {"shr", "[bc", {1, (unsigned char *)"\xBA"}, {-1, 0, 0}},
    {"shr", "[hl", {1, (unsigned char *)"\xBB"}, {-1, 0, 0}},
    {"ror", "a", {1, (unsigned char *)"\xC1"}, {-1, 0, 0}},
    {"ror", "[bc", {1, (unsigned char *)"\xBE"}, {-1, 0, 0}},
    {"ror", "[hl", {1, (unsigned char *)"\xBF"}, {-1, 0, 0}},

    {"sto", "[bc_a", {2, (unsigned char *)"\x2C\x98"}, {-1, 0, 0}},
    {"sto", "[bc_b", {2, (unsigned char *)"\x2C\x99"}, {-1, 0, 0}},
    {"sto", "[bc_c", {2, (unsigned char *)"\x2C\x9A"}, {-1, 0, 0}},
    {"sto", "[bc_d", {2, (unsigned char *)"\x2C\x9B"}, {-1, 0, 0}},
    {"sto", "[bc_h", {2, (unsigned char *)"\x2C\x9C"}, {-1, 0, 0}},
    {"sto", "[bc_l", {2, (unsigned char *)"\x2C\x9D"}, {-1, 0, 0}},
    {"sto", "[bc_psw", {2, (unsigned char *)"\x2C\x9E"}, {-1, 0, 0}},
    {"sto", "[bc_bc", {2, (unsigned char *)"\x2C\xA1"}, {-1, 0, 0}},
    {"sto", "[bc_hl", {2, (unsigned char *)"\x2C\xA2"}, {-1, 0, 0}},
    {"sto", "[bc_sp", {2, (unsigned char *)"\x2C\xA3"}, {-1, 0, 0}},
    {"sto", "[bc_pc", {2, (unsigned char *)"\x2C\xA4"}, {-1, 0, 0}},
    {"sto", "[hl_a", {2, (unsigned char *)"\x2D\x98"}, {-1, 0, 0}},
    {"sto", "[hl_b", {2, (unsigned char *)"\x2D\x99"}, {-1, 0, 0}},
    {"sto", "[hl_c", {2, (unsigned char *)"\x2D\x9A"}, {-1, 0, 0}},
    {"sto", "[hl_d", {2, (unsigned char *)"\x2D\x9B"}, {-1, 0, 0}},
    {"sto", "[hl_h", {2, (unsigned char *)"\x2D\x9C"}, {-1, 0, 0}},
    {"sto", "[hl_l", {2, (unsigned char *)"\x2D\x9D"}, {-1, 0, 0}},
    {"sto", "[hl_psw", {2, (unsigned char *)"\x2D\x9E"}, {-1, 0, 0}},
    {"sto", "[hl_bc", {2, (unsigned char *)"\x2D\xA1"}, {-1, 0, 0}},
    {"sto", "[hl_hl", {2, (unsigned char *)"\x2D\xA2"}, {-1, 0, 0}},
    {"sto", "[hl_sp", {2, (unsigned char *)"\x2D\xA3"}, {-1, 0, 0}},
    {"sto", "[hl_pc", {2, (unsigned char *)"\x2D\xA4"}, {-1, 0, 0}},
    {"sto", "[sp_a", {2, (unsigned char *)"\x2E\x98"}, {-1, 0, 0}},
    {"sto", "[sp_b", {2, (unsigned char *)"\x2E\x99"}, {-1, 0, 0}},
    {"sto", "[sp_c", {2, (unsigned char *)"\x2E\x9A"}, {-1, 0, 0}},
    {"sto", "[sp_d", {2, (unsigned char *)"\x2E\x9B"}, {-1, 0, 0}},
    {"sto", "[sp_h", {2, (unsigned char *)"\x2E\x9C"}, {-1, 0, 0}},
    {"sto", "[sp_l", {2, (unsigned char *)"\x2E\x9D"}, {-1, 0, 0}},
    {"sto", "[sp_psw", {2, (unsigned char *)"\x2E\x9E"}, {-1, 0, 0}},
    {"sto", "[sp_bc", {2, (unsigned char *)"\x2E\xA1"}, {-1, 0, 0}},
    {"sto", "[sp_hl", {2, (unsigned char *)"\x2E\xA2"}, {-1, 0, 0}},
    {"sto", "[sp_sp", {2, (unsigned char *)"\x2E\xA3"}, {-1, 0, 0}},
    {"sto", "[sp_pc", {2, (unsigned char *)"\x2E\xA4"}, {-1, 0, 0}},
    {"sto", "[pc_a", {2, (unsigned char *)"\x2F\x98"}, {-1, 0, 0}},
    {"sto", "[pc_b", {2, (unsigned char *)"\x2F\x99"}, {-1, 0, 0}},
    {"sto", "[pc_c", {2, (unsigned char *)"\x2F\x9A"}, {-1, 0, 0}},
    {"sto", "[pc_d", {2, (unsigned char *)"\x2F\x9B"}, {-1, 0, 0}},
    {"sto", "[pc_h", {2, (unsigned char *)"\x2F\x9C"}, {-1, 0, 0}},
    {"sto", "[pc_l", {2, (unsigned char *)"\x2F\x9D"}, {-1, 0, 0}},
    {"sto", "[pc_psw", {2, (unsigned char *)"\x2F\x9E"}, {-1, 0, 0}},
    {"sto", "[pc_bc", {2, (unsigned char *)"\x2F\xA1"}, {-1, 0, 0}},
    {"sto", "[pc_hl", {2, (unsigned char *)"\x2F\xA2"}, {-1, 0, 0}},
    {"sto", "[pc_sp", {2, (unsigned char *)"\x2F\xA3"}, {-1, 0, 0}},
    {"sto", "[pc_pc", {2, (unsigned char *)"\x2F\xA4"}, {-1, 0, 0}},
    {"sto", "m_a", {3, (unsigned char *)"\x40\x00\x00"}, {0, 1, 2}},
    {"sto", "m_b", {3, (unsigned char *)"\x41\x00\x00"}, {0, 1, 2}},
    {"sto", "m_c", {3, (unsigned char *)"\x42\x00\x00"}, {0, 1, 2}},
    {"sto", "m_d", {3, (unsigned char *)"\x43\x00\x00"}, {0, 1, 2}},
    {"sto", "m_h", {3, (unsigned char *)"\x44\x00\x00"}, {0, 1, 2}},
    {"sto", "m_l", {3, (unsigned char *)"\x45\x00\x00"}, {0, 1, 2}},
    {"sto", "m_psw", {3, (unsigned char *)"\x46\x00\x00"}, {0, 1, 2}},

    {"swp", "a_b", {1, (unsigned char *)"\x63"}, {-1, 0, 0}},
    {"swp", "a_c", {1, (unsigned char *)"\x64"}, {-1, 0, 0}},
    {"swp", "a_d", {1, (unsigned char *)"\x65"}, {-1, 0, 0}},
    {"swp", "a_h", {1, (unsigned char *)"\x66"}, {-1, 0, 0}},
    {"swp", "a_l", {1, (unsigned char *)"\x67"}, {-1, 0, 0}},
    {"swp", "a_psw", {1, (unsigned char *)"\x68"}, {-1, 0, 0}},

    {"xor", "a_[bc", {1, (unsigned char *)"\xA8"}, {-1, 0, 0}},
    {"xor", "a_[hl", {1, (unsigned char *)"\xA9"}, {-1, 0, 0}},
    {"xor", "a_[m", {3, (unsigned char *)"\xAA\x00\x00"}, {1, 1, 2}},
    {"xor", "a_a", {1, (unsigned char *)"\xA0"}, {-1, 0, 0}},
    {"xor", "a_b", {1, (unsigned char *)"\xA1"}, {-1, 0, 0}},
    {"xor", "a_c", {1, (unsigned char *)"\xA2"}, {-1, 0, 0}},
    {"xor", "a_d", {1, (unsigned char *)"\xA3"}, {-1, 0, 0}},
    {"xor", "a_h", {1, (unsigned char *)"\xA4"}, {-1, 0, 0}},
    {"xor", "a_l", {1, (unsigned char *)"\xA5"}, {-1, 0, 0}},
    {"xor", "a_m", {2, (unsigned char *)"\xA7\x00"}, {1, 1, 1}},
    {"xor", "a_psw", {1, (unsigned char *)"\xA6"}, {-1, 0, 0}},

    {NULL, NULL, {0, NULL}, {0, 0, 0}}
};

const Instruction *findInstructionByName(char *instruction, char *types)
{
    for (int i = 0; ISA[i].name; i++)
    {
        const Instruction *ins = &ISA[i];
        if (strcasecmp(ins->name, instruction) == 0 && strcasecmp(ins->signature, types) == 0)
            return ins;
    }

    return NULL;
}
